# -*- coding: utf-8 -*-
"""Cattle_detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zqS6tCAgVDzWiX7m8sBozld94ll1dFgA
"""

# using the best weights!
python detect.py --weights /content/DATA298B/best.pt --img 704 --conf 0.3 --source /content/DATA298B/ProducersLivestock --save-txt

import glob

def read_all_lines(file):
    """Gets all lines from a file.
    Returns:
    str
        all lines of the input file
    """
    with open(file, 'rt') as fd:
        all_lines = fd.read()
    return all_lines

def merge_per_folder(folder_path, all_files_lines_filename, total_number_filename):
    """Merges all lines of text files in one folder, and writes combined lines into new output file
    Parameters:
    folder_path : str
        String representation of the folder path containing the text files.
    all_files_lines_filename : str
        Name of the output file the merged lines will be written to.
    total_number_filename : str
        Name of the output file the number of lines in all_files_lines_filename will be written to.
    """ 
    # making sure there's a slash to the folder path 
    folder_path += "" if folder_path[-1] == "/" else "/"
    # getting all text files
    txt_files = glob.glob(folder_path + "*.txt")
    # getting all lines; map to each text file (sorted)
    output_strings = map(read_all_lines, sorted(txt_files))
    output_content = "".join(output_strings)
    # writing to all_files_lines_filename
    with open(folder_path + all_files_lines_filename, 'wt') as outfile:
        outfile.write(output_content)
    # counting lines in all_files_lines_filename   
    with open(folder_path + all_files_lines_filename, 'r') as fp:
       num_detected_cattle = sum(1 for line in fp if line.rstrip())
       print('\nTotal number of detected cattle:', num_detected_cattle)  
    # writing to total_number_filename
    with open(folder_path + total_number_filename, 'wt') as total_number_file:
        total_number_file.write(str(num_detected_cattle))

# getting the latest exp file in runs folder
def latest_exp(b='.'):
  result = []
  for d in os.listdir(b):
    bd = os.path.join(b, d)
    if os.path.isdir(bd): result.append(bd)
  main_folder_path = str(result[len(result) - 1])
  #print('Path of exp folder for the latest detection: ', main_folder_path)
  return main_folder_path
folder_path = (latest_exp('/content/DATA298B/runs/detect')+'/labels')
#print('Path to saved labels of each image detection: ', folder_path)
merge_per_folder(folder_path, 'all_lins_in_files','cattle_total_number')

print('cattle_total_number ',cattle_total_number)
